services:
  go: &go
    env_file: .env
    tty: true
    stdin_open: true
    build:
      context: .
      target: build
    entrypoint: go
    command: help
    volumes:
      - .:/usr/src/app:delegated
      - gomod:/go/pkg/mod
      - ${LOCAL_DEP_PATH:-..}:/local

  app:
    <<: *go
    command: run ./cmd/graph/main.go
    ports:
      - ${PORT}:8080

  gen:
    <<: *go
    command: run github.com/99designs/gqlgen

volumes:
  gomod: {}
