---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: person-service
  annotations:
    fluxcd.io/automated: "true"
spec:
  selector:
    matchLabels:
      app: person-service
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: person-service
    spec:
      restartPolicy: Always
      imagePullSecrets:
        - name: registry-auth
      containers:
        - name: person-service
          image: ghcr.io/compada/person-service:sha-a5eeb4b
          imagePullPolicy: IfNotPresent
          ports:
            - name: web
              containerPort: 8080
          envFrom:
            - configMapRef:
                name: person-service-config
          resources:
            requests:
              cpu: 50m
              memory: 200M
            limits:
              cpu: 100m
              memory: 400M
